# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datastore.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='datastore.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x64\x61tastore.proto\"\x17\n\x07Request\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"&\n\x08Request2\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x18\n\x08Response\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\'\n\tResponse2\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x14\n\x12ReplicationRequest\"/\n\x11ReplicationStream\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t2\xc8\x01\n\tDatastore\x12\x1c\n\x03put\x12\x08.Request\x1a\t.Response\"\x00\x12\x1c\n\x03get\x12\x08.Request\x1a\t.Response\"\x00\x12\x1f\n\x04get2\x12\t.Request2\x1a\n.Response2\"\x00\x12$\n\x07hw2_put\x12\x08.Request\x1a\t.Response\"\x00(\x01\x30\x01\x12\x38\n\tconnector\x12\x13.ReplicationRequest\x1a\x12.ReplicationStream\"\x00\x30\x01\x62\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Request.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=42,
)


_REQUEST2 = _descriptor.Descriptor(
  name='Request2',
  full_name='Request2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Request2.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Request2.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=82,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Response.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=108,
)


_RESPONSE2 = _descriptor.Descriptor(
  name='Response2',
  full_name='Response2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Response2.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Response2.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=149,
)


_REPLICATIONREQUEST = _descriptor.Descriptor(
  name='ReplicationRequest',
  full_name='ReplicationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=171,
)


_REPLICATIONSTREAM = _descriptor.Descriptor(
  name='ReplicationStream',
  full_name='ReplicationStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ReplicationStream.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='ReplicationStream.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=220,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Request2'] = _REQUEST2
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Response2'] = _RESPONSE2
DESCRIPTOR.message_types_by_name['ReplicationRequest'] = _REPLICATIONREQUEST
DESCRIPTOR.message_types_by_name['ReplicationStream'] = _REPLICATIONSTREAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'datastore_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  ))
_sym_db.RegisterMessage(Request)

Request2 = _reflection.GeneratedProtocolMessageType('Request2', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST2,
  __module__ = 'datastore_pb2'
  # @@protoc_insertion_point(class_scope:Request2)
  ))
_sym_db.RegisterMessage(Request2)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'datastore_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  ))
_sym_db.RegisterMessage(Response)

Response2 = _reflection.GeneratedProtocolMessageType('Response2', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE2,
  __module__ = 'datastore_pb2'
  # @@protoc_insertion_point(class_scope:Response2)
  ))
_sym_db.RegisterMessage(Response2)

ReplicationRequest = _reflection.GeneratedProtocolMessageType('ReplicationRequest', (_message.Message,), dict(
  DESCRIPTOR = _REPLICATIONREQUEST,
  __module__ = 'datastore_pb2'
  # @@protoc_insertion_point(class_scope:ReplicationRequest)
  ))
_sym_db.RegisterMessage(ReplicationRequest)

ReplicationStream = _reflection.GeneratedProtocolMessageType('ReplicationStream', (_message.Message,), dict(
  DESCRIPTOR = _REPLICATIONSTREAM,
  __module__ = 'datastore_pb2'
  # @@protoc_insertion_point(class_scope:ReplicationStream)
  ))
_sym_db.RegisterMessage(ReplicationStream)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class DatastoreStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.put = channel.unary_unary(
          '/Datastore/put',
          request_serializer=Request.SerializeToString,
          response_deserializer=Response.FromString,
          )
      self.get = channel.unary_unary(
          '/Datastore/get',
          request_serializer=Request.SerializeToString,
          response_deserializer=Response.FromString,
          )
      self.get2 = channel.unary_unary(
          '/Datastore/get2',
          request_serializer=Request2.SerializeToString,
          response_deserializer=Response2.FromString,
          )
      self.hw2_put = channel.stream_stream(
          '/Datastore/hw2_put',
          request_serializer=Request.SerializeToString,
          response_deserializer=Response.FromString,
          )
      self.connector = channel.unary_stream(
          '/Datastore/connector',
          request_serializer=ReplicationRequest.SerializeToString,
          response_deserializer=ReplicationStream.FromString,
          )


  class DatastoreServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def put(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def get2(self, request, context):
      """Put request to accomodate for replication 
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def hw2_put(self, request_iterator, context):
      """Automatically puts 'put' requests into master db 
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def connector(self, request, context):
      """Connects the slave server with master server for replication 
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_DatastoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'put': grpc.unary_unary_rpc_method_handler(
            servicer.put,
            request_deserializer=Request.FromString,
            response_serializer=Response.SerializeToString,
        ),
        'get': grpc.unary_unary_rpc_method_handler(
            servicer.get,
            request_deserializer=Request.FromString,
            response_serializer=Response.SerializeToString,
        ),
        'get2': grpc.unary_unary_rpc_method_handler(
            servicer.get2,
            request_deserializer=Request2.FromString,
            response_serializer=Response2.SerializeToString,
        ),
        'hw2_put': grpc.stream_stream_rpc_method_handler(
            servicer.hw2_put,
            request_deserializer=Request.FromString,
            response_serializer=Response.SerializeToString,
        ),
        'connector': grpc.unary_stream_rpc_method_handler(
            servicer.connector,
            request_deserializer=ReplicationRequest.FromString,
            response_serializer=ReplicationStream.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Datastore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaDatastoreServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def put(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def get(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def get2(self, request, context):
      """Put request to accomodate for replication 
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def hw2_put(self, request_iterator, context):
      """Automatically puts 'put' requests into master db 
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def connector(self, request, context):
      """Connects the slave server with master server for replication 
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaDatastoreStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def put(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    put.future = None
    def get(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    get.future = None
    def get2(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Put request to accomodate for replication 
      """
      raise NotImplementedError()
    get2.future = None
    def hw2_put(self, request_iterator, timeout, metadata=None, with_call=False, protocol_options=None):
      """Automatically puts 'put' requests into master db 
      """
      raise NotImplementedError()
    def connector(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Connects the slave server with master server for replication 
      """
      raise NotImplementedError()


  def beta_create_Datastore_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('Datastore', 'connector'): ReplicationRequest.FromString,
      ('Datastore', 'get'): Request.FromString,
      ('Datastore', 'get2'): Request2.FromString,
      ('Datastore', 'hw2_put'): Request.FromString,
      ('Datastore', 'put'): Request.FromString,
    }
    response_serializers = {
      ('Datastore', 'connector'): ReplicationStream.SerializeToString,
      ('Datastore', 'get'): Response.SerializeToString,
      ('Datastore', 'get2'): Response2.SerializeToString,
      ('Datastore', 'hw2_put'): Response.SerializeToString,
      ('Datastore', 'put'): Response.SerializeToString,
    }
    method_implementations = {
      ('Datastore', 'connector'): face_utilities.unary_stream_inline(servicer.connector),
      ('Datastore', 'get'): face_utilities.unary_unary_inline(servicer.get),
      ('Datastore', 'get2'): face_utilities.unary_unary_inline(servicer.get2),
      ('Datastore', 'hw2_put'): face_utilities.stream_stream_inline(servicer.hw2_put),
      ('Datastore', 'put'): face_utilities.unary_unary_inline(servicer.put),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Datastore_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('Datastore', 'connector'): ReplicationRequest.SerializeToString,
      ('Datastore', 'get'): Request.SerializeToString,
      ('Datastore', 'get2'): Request2.SerializeToString,
      ('Datastore', 'hw2_put'): Request.SerializeToString,
      ('Datastore', 'put'): Request.SerializeToString,
    }
    response_deserializers = {
      ('Datastore', 'connector'): ReplicationStream.FromString,
      ('Datastore', 'get'): Response.FromString,
      ('Datastore', 'get2'): Response2.FromString,
      ('Datastore', 'hw2_put'): Response.FromString,
      ('Datastore', 'put'): Response.FromString,
    }
    cardinalities = {
      'connector': cardinality.Cardinality.UNARY_STREAM,
      'get': cardinality.Cardinality.UNARY_UNARY,
      'get2': cardinality.Cardinality.UNARY_UNARY,
      'hw2_put': cardinality.Cardinality.STREAM_STREAM,
      'put': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'Datastore', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
